### ISSUE TITLE
Changes to Apache Web Server Doc

### ISSUE THREAD

**Issue by cwurld** [saxix/django-site-maintenance#1]
Hi,

Thanks for posting this app. It works great. However, It seems there is a typo in the Apache Config in the docs. Currently the line is:

RewriteRule ^(.+) $MAINTENANCE_URL [RL]

That gives me an error. This seems to work (added a comma between RL):

RewriteRule ^(.+) $MAINTENANCE_URL [R,L]

Also, could you explain more what this line does:

RewriteCond %{REQUEST_URI} !/$STATIC_URL/maintenance/under-maintenance.gif

I am using my own maintenance.html that does not include that gif. Yet things still seem to work.

Thanks again,
Chuck

**Comment by saxix** [comment]
RewriteRule was broken, thanks for the notice, RewriteCond is needed to not "rewrite" the requests to the image contained into the default maintenance page
